## House Prices : Advance Regression Technique

Data Analysis Life Cycle 
- Data Analysis 
- Feature Engineering 
- Feature Selection 
- Model Building 
- Model Deployment

In [4]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv('datasets/House_train.csv')

In [6]:
dataset.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In Data Analysis we will Analyze to find out the below stuff 
1. Missing Values 
2. All the Numerical Variables 
3. Distriibution of the Numerical variables 
4. Categorical Variables 
5. Cardibality of ategorical variables 
6. Outliers 
7. Realationship betwen independent and dependent features

### Missing Values

In [7]:
features_with_na = [feature for feature in dataset.columns if dataset[feature].isnull().sum()]

In [8]:
for feature in features_with_na:
    print(feature,np.round(dataset[feature].isnull().mean()),4)

LotFrontage 0.0 4
Alley 1.0 4
MasVnrType 1.0 4
MasVnrArea 0.0 4
BsmtQual 0.0 4
BsmtCond 0.0 4
BsmtExposure 0.0 4
BsmtFinType1 0.0 4
BsmtFinType2 0.0 4
Electrical 0.0 4
FireplaceQu 0.0 4
GarageType 0.0 4
GarageYrBlt 0.0 4
GarageFinish 0.0 4
GarageQual 0.0 4
GarageCond 0.0 4
PoolQC 1.0 4
Fence 1.0 4
MiscFeature 1.0 4

In [9]:
import matplotlib.pyplot as plt
import numpy as np

# Loop through features with missing values
for feature in features_with_na:
    # Create a binary indicator: 1 if missing, 0 if not
    data[feature + '_na'] = np.where(data[feature].isnull(), 1, 0)

    # Plot the median SalePrice for missing vs. non-missing values
    data.groupby(feature + '_na')['SalePrice'].median().plot.bar()
    plt.title(f'{feature} - Missing vs Non-Missing')
    plt.xlabel('Missing (1) vs Not Missing (0)')
    plt.ylabel('Median SalePrice')
    plt.show()

NameError: name 'data' is not defined